version: '3'
services:
  web:
    image: trzl/portfolio:boltnetwork-web_v1
    container_name: boltnetwork-web
    restart: unless-stopped
    expose:
      - "80"
      - "443"
    environment:
      VIRTUAL_HOST: boltnetwork.tbrownkcdev.com
      LETSENCRYPT_HOST: boltnetwork.tbrownkcdev.com
      LETSENCRYPT_EMAIL: brownty47@gmail.com
networks:
  default:
    external:
      name: webproxy
